In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('/Users/pratiksha/Documents/scratch/Computer_vision_rpsn_game/Rock_paper_scissors_nothing/keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0] > 0.5:
        print("Rock")
    elif prediction[0][1] > 0.5:
        print("Paper")
    elif prediction[0][2] > 0.5:
        print("Scissors")
    else:
        print("Nothing")       
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-05-25 19:11:07.284689: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-25 19:11:07.285070: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


2022-05-25 19:11:08.431516: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-05-25 19:11:08.591314: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 405ms/step
Nothing
[[0.05643355 0.1796502  0.00684855 0.7570677 ]]
1/1 [==============================] - 0s 17ms/step
Nothing
[[0.12000816 0.41797006 0.00176662 0.46025512]]
1/1 [==============================] - 0s 15ms/step
Nothing
[[0.08059634 0.45215365 0.00172584 0.4655242 ]]
1/1 [==============================] - 0s 15ms/step
Nothing
[[0.07280728 0.37898228 0.00280658 0.5454039 ]]
1/1 [==============================] - 0s 15ms/step
Nothing
[[0.07273709 0.35203138 0.00355088 0.5716806 ]]
1/1 [==============================] - 0s 16ms/step
Nothing
[[0.10055564 0.46507114 0.00142387 0.43294936]]
1/1 [==============================] - 0s 16ms/step
Nothing
[[0.14871137 0.38035485 0.00178338 0.46915045]]
1/1 [==============================] - 0s 15ms/step
Nothing
[[0.28495494 0.36473793 0.00262302 0.34768417]]
1/1 [==============================] - 0s 15ms/step
Nothing
[[0.29667097 0.28406426 0.00260708 0.4166578 ]]
1/1 [======================

KeyboardInterrupt: 